aws_region          = "ap-south-1"
aws_account_id      = "432049653779"
ecr_repository_name = "springboot-app"
github_org          = "Arudra20"
github_repo         = "eks-end-to-end-pipeline"
eks_cluster_name    = "my-eks-cluster"
kubernetes_namespace = "dev"
