aws_region          = "ap-south-1"
aws_account_id      = "526123658224"
ecr_repository_name = "springboot-app"
github_org          = "ramyakolupula25"
github_repo         = "EKS-PROJECT"
eks_cluster_name    = "eks-cluster"
kubernetes_namespace = "dev"
