replicaCount: 2

image:
  repository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/springboot-app"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  host: ""
  path: /
  healthcheckPath: /actuator/health/readiness

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
